version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # MongoDB Atlas connection (set your own connection string)
      - MONGO_URI=mongodb://localhost:27017
      - MONGO_DB_NAME=ai_copilot
      # Ollama configuration (assumes Ollama running on host)
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
      - EMBEDDING_MODEL=nomic-embed-text
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # MongoDB Atlas connection (set your own connection string)
      - MONGO_URI=mongodb://localhost:27017
      - MONGO_DB_NAME=ai_copilot
      # Ollama configuration (assumes Ollama running on host)
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2
      - EMBEDDING_MODEL=nomic-embed-text
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=2

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A app.workers.celery_app flower --port=5555

  # Optional: Local MongoDB for development (comment out if using Atlas)
  # mongodb:
  #   image: mongo:7
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: ai_copilot

volumes:
  redis_data:
  # mongodb_data:  # Uncomment if using local MongoDB
